### ISSUE TITLE
Set up a **Dockerized MySQL database with an Express.js API** on an **Ubuntu server**

### ISSUE THREAD

**Issue by KyleFick** [KyleFick/Next.js-Employee-System#1]
---

## ✅ Goal:
- MySQL runs in a Docker container
- Express API runs in another container (or locally)
- Data is persisted in a volume
- Everything can be started with Docker Compose

---

### 1. **Create Project Folder**
```bash
mkdir express-mysql-api && cd express-mysql-api
```

---

### 2. **Create Docker Compose File**
Create `docker-compose.yml`:
```yaml
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
```

---

### 3. **Initialize Express API**
```bash
mkdir api && cd api
npm init -y
npm install express mysql2 dotenv
```

Create `.env` file:
```env
DB_HOST=mysql
DB_USER=user
DB_PASSWORD=userpass
DB_NAME=mydb
DB_PORT=3306
```

Create `index.js`:
```js
require('dotenv').config();
const express = require('express');
const mysql = require('mysql2');

const app = express();
const port = 3000;

const db = mysql.createConnection({
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  port: process.env.DB_PORT
});

db.connect(err => {
  if (err) throw err;
  console.log('Connected to MySQL');
});

app.get('/', (req, res) => {
  db.query('SELECT NOW()', (err, results) => {
    if (err) throw err;
    res.send(results);
  });
});

app.listen(port, () => console.log(`API listening on port ${port}`));
```

---

### 4. **Add Dockerfile for Express API**
Create `api/Dockerfile`:
```dockerfile
FROM node:18

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["node", "index.js"]
```

---

### 5. **Update Docker Compose to Include API**
Back in the root folder, update `docker-compose.yml`:
```yaml
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build: ./api
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: mydb
      DB_PORT: 3306

volumes:
  mysql-data:
```

---

### 6. **Start Everything**
```bash
docker-compose up --build
```

- Express API: [http://your-server-ip:3000](http://your-server-ip:3000)
- MySQL: available on port `3306` to containers (or external tools)

---

## ✅ Optional Extras
- Use **Adminer** or **phpMyAdmin** as a web GUI by adding another service
- Add **Nginx reverse proxy** for production use
- Add **JWT Auth**, **CORS**, and routing as needed

---

Would you like me to generate this full project as a downloadable ZIP or GitHub repo format for you?
